stem_subjects = [
    'Subjects allied to medicine',
    'Agriculture, food and related studies',
    'Biological and sport sciences',
    'Computing',
    'Engineering and technology',
    'Physical sciences',
    'Mathematical sciences',
    'Medicine and dentistry',
    'Veterinary sciences',
    'Allied health',
    'Engineering',
    'General, applied and forensic sciences',
    'Medical sciences',
    'Nursing and midwifery',
    'Sport and exercise sciences',
    'Biosciences',
    'Physics and astronomy',
    'Chemistry',
    'Materials and technology',
    'Pharmacology, toxicology and pharmacy',
    'Biomedical sciences (non-specific)',
    'Business and management (non-specific)',
    'Civil engineering',
    'Computer games and animation',
    'Design studies',
    'Food and beverage studies (non-specific)',
    'Forensic and archaeological sciences',
    'Mental health nursing',
    'Others in computing',
    'Psychology (non-specific)',
    'Psychology and health',
    'Social sciences (non-specific)',
    'Software engineering',
    'Agriculture',
    'Animal science',
    'Applied psychology',
    'Artificial intelligence',
    'Astronomy',
    'Biology (non-specific)',
    'Business studies',
    'Cinematics and photography',
    'Computer science',
    'Counselling, psychotherapy and occupational therapy',
    'Creative writing',
    'Ecology and environmental biology',
    'Environmental sciences',
    'Finance',
    'Genetics',
    'Health sciences (non-specific)',
    'Information systems',
    'Management studies',
    'Mathematics',
    'Molecular biology, biophysics and biochemistry',
    'Physical geographical sciences',
    'Physics',
    'Production and manufacturing engineering',
    'Adult nursing',
    'Building',
    "Children's nursing",
    'Health studies',
    'Human resource management',
    'Mechanical engineering',
    'Medicine (non-specific)',
    'Midwifery',
    'Nursing (non-specific)',
    'Ophthalmics',
    'Performing arts (non-specific)',
    'Information technology',
    'Others in veterinary sciences',
    'Bioengineering, medical and biomedical engineering',
    'Biosciences (non-specific)',
    'Business computing',
    'Chemical, process and energy engineering',
    'Electrical and electronic engineering',
    'English language',
    'Healthcare science (non-specific)',
    'Others in technology',
    'Pharmacy',
    'Earth sciences',
    'Forestry and arboriculture',
    'Geography (non-specific)',
    'Medical sciences (non-specific)',
    'Medical technology',
    'Nutrition and dietetics',
    'Engineering (non-specific)',
    'Food sciences',
    'Minerals technology',
    'Planning (urban, rural and regional)',
    'Polymers and textiles',
    'Physiotherapy',
    'Aeronautical and aerospace engineering',
    'Statistics',
    'Others in biosciences',
    'Environmental and public health',
    'Dental nursing',
    'Dentistry',
    'Pharmacology',
    'Food and beverage production',
    'Materials technology',
    'Toxicology',
    'Anatomy, physiology and pathology',
    'Natural sciences (non-specific)',
    'Operational research',
    'Microbiology and cell science',
    'Veterinary medicine and dentistry',
    'Materials science',
    'Maritime technology',
    'Naval architecture',
    'Agricultural sciences',
    'Others in nursing',
    'Biotechnology',
    'Others in engineering',
    'Sciences (non-specific)',
    'Others in Celtic studies','Medicine by specialism','Zoology'
]
humanities_subjects = [
    'Design, and creative and performing arts', 
    'Law',
    'Psychology',
    'Social sciences',
    'Education and teaching',
    'Geography, earth and environmental studies',
    'Historical, philosophical and religious studies',
    'Language and area studies',
    'Media, journalism and communications',
    'Architecture, building and planning',
    'Performing arts',
    'Creative arts and design',
    'Sociology, social policy and anthropology',
    'Celtic studies',
    'Economics',
    'English studies',
    'History and archaeology',
    'Languages and area studies',
    'Politics',
    'Philosophy and religious studies',
    'Music',
    'Complementary and alternative medicine',
    'Accounting',
    'Marketing',
    'Sociology',
    'Art',
    'Drama',
    'Education',
    'French studies',
    'History',
    'Human geography',
    'Iberian studies',
    'Literature in English',
    'Media studies',
    'Social policy',
    'Welsh studies',
    'Childhood and youth studies',
    'Philosophy',
    'Social work',
    'Tourism, transport and travel',
    'Dance',
    'Journalism',
    'Learning disabilities nursing',
    'Linguistics',
    'Teacher training',
    'Theology and religious studies',
    'Heritage studies',
    'History of art, architecture and design',
    'Classics',
    'Development studies',
    'Publicity studies',
    'Information services',
    'American and Australasian studies',
    'Cultural studies',
    'African and modern Middle Eastern studies',
    'Humanities (non-specific)',
    'Others in language and area studies',
    'Others in psychology',
    'Others in creative arts and design',
    'Anthropology',
    'Archaeology',
    'Rural estate management',
    'Combined, general or negotiated studies',
    'Developmental psychology',
    'Asian studies',
    'German and Scandinavian studies',
    'Italian studies',
    'Liberal arts (non-specific)',
    'Slavic studies',
    'Landscape design', 'Business and management', 'Combined and general studies','Health and social care',
    'Architecture','Creative arts and design (non-specific)', 'Personal development', 'Publishing','Hair and beauty sciences',
    'English studies (non-specific)', 'Others in business and management' 
]
full_list = [
    'Design, and creative and performing arts', 'Subjects allied to medicine',
    'Agriculture, food and related studies', 'Biological and sport sciences',
    'Business and management', 'Computing', 'Engineering and technology', 'Law',
    'Physical sciences', 'Psychology', 'Social sciences',
    'Education and teaching', 'Geography, earth and environmental studies',
    'Historical, philosophical and religious studies',
    'Language and area studies', 'Mathematical sciences',
    'Media, journalism and communications',
    'Architecture, building and planning', 'Medicine and dentistry',
    'Veterinary sciences', 'Combined and general studies', 'Performing arts',
    'Allied health', 'Creative arts and design', 'Engineering',
    'General, applied and forensic sciences', 'Medical sciences',
    'Nursing and midwifery', 'Sociology, social policy and anthropology',
    'Sport and exercise sciences', 'Biosciences', 'Celtic studies', 'Economics',
    'English studies', 'History and archaeology', 'Languages and area studies',
    'Physics and astronomy', 'Politics', 'Health and social care',
    'Philosophy and religious studies', 'Chemistry', 'Materials and technology',
    'Pharmacology, toxicology and pharmacy', 'Music',
    'Complementary and alternative medicine', 'Accounting',
    'Biomedical sciences (non-specific)',
    'Business and management (non-specific)', 'Civil engineering',
    'Computer games and animation', 'Design studies',
    'Food and beverage studies (non-specific)',
    'Forensic and archaeological sciences', 'Marketing',
    'Mental health nursing', 'Others in computing', 'Psychology (non-specific)',
    'Psychology and health', 'Social sciences (non-specific)', 'Sociology',
    'Software engineering', 'Agriculture', 'Animal science',
    'Applied psychology', 'Art', 'Artificial intelligence', 'Astronomy',
    'Biology (non-specific)', 'Business studies', 'Cinematics and photography',
    'Computer science', 'Counselling, psychotherapy and occupational therapy',
    'Creative writing', 'Drama', 'Ecology and environmental biology',
    'Education', 'Environmental sciences', 'Finance', 'French studies',
    'Genetics', 'Health sciences (non-specific)', 'History', 'Human geography',
    'Iberian studies', 'Information systems', 'Literature in English',
    'Management studies', 'Mathematics', 'Media studies',
    'Molecular biology, biophysics and biochemistry',
    'Physical geographical sciences', 'Physics',
    'Production and manufacturing engineering', 'Social policy',
    'Welsh studies', 'Zoology', 'Adult nursing', 'Architecture', 'Building',
    'Childhood and youth studies', "Children's nursing", 'Health studies',
    'Human resource management', 'Mechanical engineering',
    'Medicine (non-specific)', 'Midwifery', 'Nursing (non-specific)',
    'Ophthalmics', 'Performing arts (non-specific)', 'Philosophy', 'Social work',
    'Tourism, transport and travel', 'Information technology', 'Dance',
    'Creative arts and design (non-specific)', 'Others in veterinary sciences',
    'Bioengineering, medical and biomedical engineering',
    'Biosciences (non-specific)', 'Business computing',
    'Chemical, process and energy engineering',
    'Electrical and electronic engineering', 'English language',
    'Healthcare science (non-specific)', 'Others in technology',
    'Personal development', 'Pharmacy', 'Journalism', 'Earth sciences',
    'Forestry and arboriculture', 'Geography (non-specific)',
    'Learning disabilities nursing', 'Linguistics',
    'Medical sciences (non-specific)', 'Medical technology', 'Teacher training',
    'Theology and religious studies', 'Nutrition and dietetics', 'Publishing',
    'Engineering (non-specific)', 'Hair and beauty sciences',
    'English studies (non-specific)', 'Others in language and area studies',
    'Others in psychology', 'Food sciences', 'Minerals technology',
    'Others in creative arts and design',
    'Planning (urban, rural and regional)', 'Polymers and textiles',
    'Anthropology', 'Archaeology', 'Physiotherapy', 'Rural estate management',
    'Aeronautical and aerospace engineering',
    'Combined, general or negotiated studies', 'Statistics',
    'Others in biosciences', 'Developmental psychology',
    'Environmental and public health', 'Asian studies', 'Dental nursing',
    'Dentistry', 'German and Scandinavian studies', 'Italian studies',
    'Pharmacology', 'Heritage studies',
    'History of art, architecture and design',
    'Others in business and management', 'Medicine by specialism',
    'Food and beverage production', 'Materials technology', 'Classics',
    'Development studies', 'Liberal arts (non-specific)', 'Toxicology',
    'Publicity studies', 'Anatomy, physiology and pathology',
    'Information services', 'Natural sciences (non-specific)',
    'Operational research', 'American and Australasian studies',
    'Microbiology and cell science', 'Cultural studies',
    'Veterinary medicine and dentistry', 'Materials science',
    'African and modern Middle Eastern studies', 'Maritime technology',
    'Naval architecture', 'Agricultural sciences', 'Others in nursing',
    'Slavic studies', 'Biotechnology', 'Landscape design',
    'Humanities (non-specific)', 'Others in engineering',
    'Sciences (non-specific)', 'Others in Celtic studies'
]

